name: Test_Action
on:
  push:
    branches: ['main']

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: echo something
      - run: echo Peas
